export { default as Ticket } from "./Ticket"
export { default as Email } from "./Email"
export { default as Ecommerce } from "./Ecommerce"
export { default as Contacts } from "./Contacts"
export { default as Calendar } from "./Calendar"
// export { default as Area } from "./chart/Area"
// export { default as Bar } from "./chart/Bar"
export { default as TreeView } from "./TreeView"
export { default as Pricing } from "./Pricing"
export { default as SettingsPage } from "./SettingsPage"